server.address=127.0.0.1
server.port=3041
spring.application.name=coregnition-backend
coregnition.database=data/coregnition.db
coregnition.storage-root=data/projects
spring.servlet.multipart.max-file-size=300000000B
spring.servlet.multipart.max-request-size=301000000B
