server.address=127.0.0.1
server.port=8787
spring.application.name=coregnition-backend
coregnition.database=data/coregnition.db
coregnition.storage-root=data/projects
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
