import { ChangeEvent, FormEvent, useEffect, useState } from "react";

const API = "/api/v1";
const labels = ["limestone", "dolostone", "carbonaceous shale", "unknown", "mixed", "unassessable"];
type Project = { id: string; name: string };
type Asset = { id: string; originalName: string; width: number; height: number; sha256: string; projectId?: string };
type Segment = { id: string; assetId: string; startDepthFeet: number; endDepthFeet: number; orientation?: string };
type Annotation = { id: string; segmentId: string; revision: number; label: string; reviewState: string };
type Workspace = { project: Project; assets: Asset[]; segments: Segment[]; annotations: Annotation[] };

export function App() {
  const [project, setProject] = useState<Project | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [name, setName] = useState("Core description pilot");
  const [asset, setAsset] = useState<Asset | null>(null);
  const [assets, setAssets] = useState<Asset[]>([]);
  const [segment, setSegment] = useState<Segment | null>(null);
  const [segments, setSegments] = useState<Segment[]>([]);
  const [annotations, setAnnotations] = useState<Annotation[]>([]);
  const [start, setStart] = useState("0");
  const [end, setEnd] = useState("1");
  const [orientation, setOrientation] = useState("TOP_TO_BOTTOM");
  const [label, setLabel] = useState(labels[0]);
  const [review, setReview] = useState("REVIEWED");
  const [busy, setBusy] = useState("");
  const [status, setStatus] = useState({ kind: "info", text: "Create a project to begin." });
  const [fileKey, setFileKey] = useState(0);
  const [archiveKey, setArchiveKey] = useState(0);
  const step = !project ? 1 : !asset ? 2 : !segment ? 3 : 4;
  const message = (kind: string, text: string) => setStatus({ kind, text });
  async function run(action: string, task: () => Promise<void>) { setBusy(action); try { await task(); } catch (error) { message("error", error instanceof Error ? error.message : "Something went wrong. Try again."); } finally { setBusy(""); } }
  async function createProject(event: FormEvent) { event.preventDefault(); if (!name.trim()) return message("error", "Enter a project name first."); await run("project", async () => { const response = await fetch(`${API}/projects`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: name.trim() }) }); if (!response.ok) throw new Error(await errorMessage(response)); const created = await response.json(); setProject(created); setProjects((items) => [created, ...items]); message("success", "Project created. Add the first core image."); }); }
  async function importAsset(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !project) return; await run("asset", async () => { const form = new FormData(); form.append("file", file); const response = await fetch(`${API}/projects/${project.id}/assets`, { method: "POST", body: form }); if (!response.ok) throw new Error(await errorMessage(response)); const imported = await response.json(); setAsset(imported); setAssets((items) => [...items, imported]); setSegment(null); message("success", "Image imported. Set its depth interval below."); }); }
  async function createSegment(event: FormEvent) { event.preventDefault(); if (!project || !asset) return; const from = Number(start), to = Number(end); if (!Number.isFinite(from) || !Number.isFinite(to) || from < 0 || to <= from) return message("error", "End depth must be greater than start depth, using non-negative feet."); await run("segment", async () => { const response = await fetch(`${API}/projects/${project.id}/segments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ assetId: asset.id, startDepthFeet: from, endDepthFeet: to, orientation }) }); if (!response.ok) throw new Error(await errorMessage(response)); const created = await response.json(); setSegment(created); setSegments((items) => [...items, created]); message("success", "Depth interval saved. Add a reviewed lithology."); }); }
  async function annotate(event: FormEvent) { event.preventDefault(); if (!project || !segment) return; await run("annotation", async () => { const response = await fetch(`${API}/projects/${project.id}/segments/${segment.id}/annotations`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, reviewState: review }) }); if (!response.ok) throw new Error(await errorMessage(response)); const saved = await response.json(); setAnnotations((items) => [...items.filter((item) => item.segmentId !== segment.id), saved]); message("success", "Annotation saved. Your interval is ready to export."); }); }
  async function undoAnnotation() { if (!project || !segment) return; await run("undo", async () => { const response = await fetch(`${API}/projects/${project.id}/segments/${segment.id}/annotations/latest`, { method: "DELETE" }); if (!response.ok) throw new Error(await errorMessage(response)); if (response.status === 204) { setAnnotations((items) => items.filter((item) => item.segmentId !== segment.id)); setLabel(labels[0]); setReview("UNREVIEWED"); message("success", "Removed the saved description."); return; } const restored: Annotation = await response.json(); setAnnotations((items) => [...items.filter((item) => item.segmentId !== segment.id), restored]); setLabel(restored.label); setReview(restored.reviewState); message("success", "Restored the previous description revision."); }); }
  async function importArchive(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; await run("archive", async () => { const form = new FormData(); form.append("file", file); const response = await fetch(`${API}/projects/archive`, { method: "POST", body: form }); if (!response.ok) throw new Error(await errorMessage(response)); const workspace: Workspace = await response.json(); setProject(workspace.project); setProjects((items) => [workspace.project, ...items.filter((item) => item.id !== workspace.project.id)]); setAssets(workspace.assets); setAsset(workspace.assets[0] ?? null); setSegments(workspace.segments); setAnnotations(workspace.annotations); setSegment(workspace.segments[0] ?? null); const annotation = workspace.annotations.find((item) => item.segmentId === workspace.segments[0]?.id); if (annotation) { setLabel(annotation.label); setReview(annotation.reviewState); } setName(workspace.project.name); setArchiveKey((value) => value + 1); message("success", `Imported ${workspace.project.name}.`); }); }
  function selectSegment(item: Segment, availableAnnotations = annotations) { setSegment(item); const selected = assets.find((entry) => entry.id === item.assetId); if (selected) setAsset(selected); const annotation = availableAnnotations.find((entry) => entry.segmentId === item.id); if (annotation) { setLabel(annotation.label); setReview(annotation.reviewState); } }
  async function openProject(id: string) { if (!id) return reset(); await run("load", async () => { const response = await fetch(`${API}/projects/${id}`); if (!response.ok) throw new Error(await errorMessage(response)); const workspace: Workspace = await response.json(); setProject(workspace.project); setAssets(workspace.assets); setAsset(workspace.assets[0] ?? null); setSegments(workspace.segments); setAnnotations(workspace.annotations); setSegment(workspace.segments[0] ?? null); const firstAnnotation = workspace.annotations.find((item) => item.segmentId === workspace.segments[0]?.id); if (firstAnnotation) { setLabel(firstAnnotation.label); setReview(firstAnnotation.reviewState); } setName(workspace.project.name); message("success", `Loaded ${workspace.project.name} with ${workspace.assets.length} image${workspace.assets.length === 1 ? "" : "s"}.`); }); }
  function reset() { setProject(null); setAsset(null); setSegment(null); setAssets([]); setSegments([]); setAnnotations([]); setName("Core description pilot"); setFileKey((value) => value + 1); message("info", "Create a project to begin."); }
  const preview = project && asset ? `${API}/projects/${project.id}/assets/${asset.id}/content` : "";
  const steps = ["Project", "Core image", "Depth calibration", "Description"];
  useEffect(() => { fetch(`${API}/projects`).then(async (response) => response.ok && setProjects(await response.json())).catch(() => undefined); }, []);
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><b>C</b><span>coregnition</span></div><div className="topbar-actions"><label className="archive-import">{busy === "archive" ? "Importing…" : "Import archive"}<input key={archiveKey} type="file" accept="application/zip,.zip" onChange={importArchive} disabled={!!busy} /></label>{projects.length > 0 && <select className="project-picker" value={project?.id ?? ""} onChange={(event) => openProject(event.target.value)} disabled={!!busy && busy !== "load"}><option value="">Open project…</option>{projects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>}<span className="mode-pill">M1 · local workspace</span></div></header>
    <section className="hero"><div><p className="eyebrow">CORE DESCRIPTION WORKSPACE</p><h1>Turn a core photo into a traceable description.</h1><p className="lede">Create a project, calibrate depth in feet, and record the lithology decisions you want to review later.</p></div><p className="local-note"><i /> Local data stays on this machine</p></section>
    <div className={`status status-${status.kind}`} role="status"><span>{status.kind === "error" ? "!" : status.kind === "success" ? "✓" : "i"}</span>{status.text}</div>
    <section className="workspace"><aside className="rail"><p className="rail-label">WORKFLOW</p>{steps.map((item, index) => { const number = index + 1, complete = number < step; return <div className={`rail-step ${number === step ? "active" : ""} ${complete ? "complete" : ""}`} key={item}><strong>{complete ? "✓" : `0${number}`}</strong><span>{item}<small>{complete ? "Complete" : number === step ? "Current step" : "Up next"}</small></span></div>; })}{project && <button className="text-button" type="button" onClick={reset}>Start another project</button>}</aside>
      <div className="content-stack">
        <form className={`panel ${step === 1 ? "panel-focus" : ""}`} onSubmit={createProject}><Heading number="01" title="Start a project" done={!!project} /><p className="help">Give this core description session a name.</p><div className="inline-form"><label>Project name<input value={name} onChange={(event) => setName(event.target.value)} disabled={!!project} placeholder="e.g. North bench, interval A" /></label><button disabled={!!project || !!busy}>{busy === "project" ? "Creating…" : "Create project"}</button></div>{project && <p className="created">✓ <b>{project.name}</b> · Ready for image import</p>}</form>
        <section className={`panel ${step === 2 ? "panel-focus" : ""}`}><Heading number="02" title="Bring in a core image" done={!!asset} /><p className="help">PNG, JPEG, and TIFF files up to 100 MB are supported.</p><label className={`dropzone ${!project ? "disabled" : ""}`}><span className="upload-icon">↑</span><b>{busy === "asset" ? "Importing image…" : "Choose an image"}</b><small>{project ? "or drag and drop it here" : "Create a project to unlock image import"}</small><input key={fileKey} type="file" accept="image/png,image/jpeg,image/tiff" onChange={importAsset} disabled={!project || !!busy} /></label>{asset && project && <div className="asset-preview"><ImageViewer src={preview} alt={`Imported ${asset.originalName}`} /><div><b>{asset.originalName}</b><span>{asset.width} × {asset.height}px</span><small>SHA-256 {asset.sha256.slice(0, 12)}…</small></div></div>}{assets.length > 1 && <div className="record-list"><strong>Imported images</strong>{assets.map((item) => <button type="button" className={item.id === asset?.id ? "selected" : ""} key={item.id} onClick={() => { setAsset(item); setSegment(segments.find((entry) => entry.assetId === item.id) ?? null); }}>{item.originalName}<span>{item.width} × {item.height}px</span></button>)}</div>}</section>
        <form className={`panel ${step === 3 ? "panel-focus" : ""}`} onSubmit={createSegment}><Heading number="03" title="Calibrate the interval" done={!!segment} /><p className="help">Set the photographed interval in feet and confirm its orientation.</p><div className="field-grid"><label>Start depth <em>ft</em><input type="number" min="0" step="0.01" value={start} onChange={(event) => setStart(event.target.value)} disabled={!asset || !!busy} /></label><label>End depth <em>ft</em><input type="number" min="0" step="0.01" value={end} onChange={(event) => setEnd(event.target.value)} disabled={!asset || !!busy} /></label></div><div className="form-footer"><label>Image orientation<select value={orientation} onChange={(event) => setOrientation(event.target.value)} disabled={!asset || !!busy}><option value="TOP_TO_BOTTOM">Top to bottom</option><option value="BOTTOM_TO_TOP">Bottom to top</option></select></label><button disabled={!asset || !!busy}>{busy === "segment" ? "Saving…" : "Save interval"}</button></div>{segment && <p className="inline-success">✓ Interval recorded: {segment.startDepthFeet}–{segment.endDepthFeet} ft</p>}{segments.length > 0 && <div className="record-list"><strong>Saved intervals</strong>{segments.map((item) => <button type="button" className={item.id === segment?.id ? "selected" : ""} key={item.id} onClick={() => selectSegment(item)}>{item.startDepthFeet}–{item.endDepthFeet} ft<span>{item.orientation ?? ""}</span></button>)}</div>}</form>
        <form className={`panel ${step === 4 ? "panel-focus" : ""}`} onSubmit={annotate}><Heading number="04" title="Describe the lithology" /><p className="help">Choose the best current interpretation. Each save creates a revision that can be undone.</p><div className="field-grid"><label>Lithology<select value={label} onChange={(event) => setLabel(event.target.value)} disabled={!segment || !!busy}>{labels.map((value) => <option key={value}>{value}</option>)}</select></label><label>Review state<select value={review} onChange={(event) => setReview(event.target.value)} disabled={!segment || !!busy}><option value="REVIEWED">Reviewed</option><option value="UNREVIEWED">Needs review</option></select></label></div><div className="form-footer"><span className="annotation-actions"><button disabled={!segment || !!busy}>{busy === "annotation" ? "Saving…" : "Save description"}</button><button className="secondary-button" type="button" onClick={undoAnnotation} disabled={!segment || !annotations.some((item) => item.segmentId === segment.id) || !!busy}>{busy === "undo" ? "Undoing…" : "Undo last save"}</button></span>{project && <span className="export-links"><a className="export-link" href={`${API}/projects/${project.id}/export.csv`}>CSV export ↓</a><a className="export-link" href={`${API}/projects/${project.id}/archive.zip`}>Project archive ↓</a></span>}</div></form>
      </div></section><footer><span>Coregnition M1</span><span>Depth units: feet</span><span>Local-first data workflow</span></footer>
  </main>;
}
function Heading({ number, title, done }: { number: string; title: string; done?: boolean }) { return <div className="panel-heading"><div><span className="panel-number">{number}</span><h2>{title}</h2></div>{done && <span className="done-badge">Complete</span>}</div>; }
function ImageViewer({ src, alt }: { src: string; alt: string }) { const [zoom, setZoom] = useState(1); const [rotation, setRotation] = useState(0); const [offset, setOffset] = useState({ x: 0, y: 0 }); const [drag, setDrag] = useState<{ x: number; y: number; offsetX: number; offsetY: number } | null>(null); const reset = () => { setZoom(1); setRotation(0); setOffset({ x: 0, y: 0 }); }; return <div className="image-viewer-shell"><div className="image-tools"><button type="button" onClick={() => setZoom((value) => Math.min(4, value + .25))}>+</button><button type="button" onClick={() => setZoom((value) => Math.max(.5, value - .25))}>−</button><button type="button" onClick={() => setRotation((value) => (value + 90) % 360)}>↻</button><button type="button" onClick={reset}>Reset</button><span>{zoom.toFixed(2)}× · {rotation}°</span></div><div className="image-viewer" onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); setDrag({ x: event.clientX, y: event.clientY, offsetX: offset.x, offsetY: offset.y }); }} onPointerMove={(event) => { if (drag) setOffset({ x: drag.offsetX + event.clientX - drag.x, y: drag.offsetY + event.clientY - drag.y }); }} onPointerUp={() => setDrag(null)}><img src={src} alt={alt} draggable={false} style={{ transform: `translate(${offset.x}px, ${offset.y}px) scale(${zoom}) rotate(${rotation}deg)` }} /></div></div>; }
async function errorMessage(response: Response) { try { return (await response.json()).error ?? `Request failed (${response.status})`; } catch { return `Request failed (${response.status})`; } }
